artifact_uri: file:C:\Users\Usuario\Documents\Maestria Nacional\2.Semestre\1.Productos_Datos\Repositorio\PRE-08-mlflow-tracking-local-jcastrillonmo\my_mlruns/208807243520979968/7b03b0a1cd7d4183948cb30d78bf6c8a/artifacts
end_time: 1748100584634
entry_point_name: ''
experiment_id: '208807243520979968'
lifecycle_stage: active
run_id: 7b03b0a1cd7d4183948cb30d78bf6c8a
run_name: elasticnet_db91d5b2
run_uuid: 7b03b0a1cd7d4183948cb30d78bf6c8a
source_name: ''
source_type: 4
source_version: ''
start_time: 1748100584614
status: 3
tags: []
user_id: Usuario
